name: Setup anchor and build and deploy program

inputs:
  rpc:
    description: 'rpc'
    required: true
    type: string
  pid:
    description: 'program PID'
    required: true
    type: string
  pid_env_var:
    description: 'program PID env var'
    required: true
    type: string
  ssh_private_key:
    description: 'SSH private key'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup GH SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ inputs.ssh_private_key }}

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Solana
      run: |
        sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
      shell: bash

    - name: Update Solana PATH
      run: |
        echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      shell: bash

    - uses: actions/cache@v3
      name: Cache Anchor build
      id: cache-anchor
      with:
        path: ${{ env.CARGO_CACHE_PATH }}
        key: anchor-${{ runner.os }}-v0000-${{ hashFiles('**/Cargo.lock') }}
  
    - uses: nick-fields/retry@v2
      if: steps.cache-anchor.outputs.cache-hit != 'true'
      with:
        retry_wait_seconds: 300
        timeout_minutes: 20
        max_attempts: 10
        retry_on: error
        shell: bash
        command: cargo install --git https://github.com/project-serum/anchor --tag v${{ env.ANCHOR_VERSION }} anchor-cli --version ${{ env.ANCHOR_VERSION }} --locked --force
        
    - run: chmod +x ~/.cargo/bin/anchor
      shell: bash

    - name: Install Anchor
      run: |
        cargo install --git https://github.com/coral-xyz/anchor avm --locked --force && avm install latest && avm use latest && anchor --version
      shell: bash

    - name: Build
      run: |
        anchor build
      shell: bash
